# Generated by Django 4.1.7 on 2023-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricingapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='timemultiplierfactor',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
